// Package discover finds monitorable services on the current host:
// running Docker containers (via the Docker Engine API over the unix
// socket, no Docker SDK dependency) and host-level TCP listeners.
package discover

import "errors"

// ErrHostScanUnsupported is returned by ListeningPorts on platforms
// where host port scanning is not implemented (only Linux is supported).
var ErrHostScanUnsupported = errors.New("host port scan is only supported on linux")

// Service is a discovered candidate for monitoring.
type Service struct {
	// Name is the container name, or "host" for host-level listeners.
	Name  string
	Image string // full image reference; empty for host services
	// Ports are the service's own (container-private or host) TCP ports.
	Ports []int
	// Published maps container-private ports to host-published ports.
	Published map[int]int
	// Networks are the user-defined Docker networks the container is
	// attached to (default networks bridge/host/none are excluded).
	Networks []string
	// IP is the container's address on one of its networks, user-defined
	// preferred. Reachable from the host on linux only.
	IP     string
	Labels map[string]string
	Source string // "docker" or "host"
}

// ManagedLabel marks containers generated by monup itself so they are
// excluded from discovery on subsequent runs.
const ManagedLabel = "monup.managed"
