// Package render turns a plan into concrete files: Prometheus config and
// rules, Grafana provisioning, dashboards and a docker-compose stack. All
// output is deterministic so it can be diffed and committed to git.
package render

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/YusufDrymz/monup/internal/catalog"
	"github.com/YusufDrymz/monup/internal/plan"
)

// Pinned images for the core stack.
const (
	prometheusImage   = "prom/prometheus:v2.53.0"
	grafanaImage      = "grafana/grafana:11.1.4"
	nodeExporterImage = "prom/node-exporter:v1.8.2"
)

const generatedHeader = "# Generated by monup — https://github.com/YusufDrymz/monup\n"

// Files renders the full output tree as path → content. Paths are
// relative to the apply output directory.
func Files(p *plan.Plan) (map[string][]byte, error) {
	files := map[string][]byte{}

	files["prometheus/prometheus.yml"] = prometheusConfig(p)

	for _, e := range uniqueEntries(p) {
		if len(e.Alerts) > 0 {
			data, err := ruleFileFor(e)
			if err != nil {
				return nil, fmt.Errorf("render rules for %s: %w", e.Name, err)
			}
			files["prometheus/rules/"+e.Name+".yml"] = data
		}
		if e.Dashboard != nil {
			data, err := dashboardJSON(e)
			if err != nil {
				return nil, fmt.Errorf("render dashboard for %s: %w", e.Name, err)
			}
			files["grafana/dashboards/"+e.Name+".json"] = data
		}
	}

	files["grafana/provisioning/datasources/monup.yml"] = []byte(grafanaDatasource)
	files["grafana/provisioning/dashboards/monup.yml"] = []byte(grafanaProvider)

	compose := composeFile(p)
	files["docker-compose.yml"] = compose
	files[".env.example"] = envExample(compose)
	return files, nil
}

// Paths returns the sorted file list, for plan output.
func Paths(files map[string][]byte) []string {
	paths := make([]string, 0, len(files))
	for p := range files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}

// uniqueEntries returns matched entries (deduplicated: rules and
// dashboards are per service kind, not per instance) plus always-entries,
// sorted by name.
func uniqueEntries(p *plan.Plan) []catalog.Entry {
	seen := map[string]bool{}
	var entries []catalog.Entry
	for _, m := range p.Matches {
		if !seen[m.Entry.Name] {
			seen[m.Entry.Name] = true
			entries = append(entries, m.Entry)
		}
	}
	for _, e := range p.AlwaysEntries {
		if !seen[e.Name] {
			seen[e.Name] = true
			entries = append(entries, e)
		}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
	return entries
}

var envRefRe = regexp.MustCompile(`\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}`)

// envExample extracts ${VAR} / ${VAR:-default} references from the
// generated compose file into a ready-to-fill .env template.
func envExample(compose []byte) []byte {
	defaults := map[string]string{}
	for _, m := range envRefRe.FindAllStringSubmatch(string(compose), -1) {
		name, def := m[1], m[2]
		if cur, ok := defaults[name]; !ok || cur == "" {
			defaults[name] = def
		}
	}
	names := make([]string, 0, len(defaults))
	for n := range defaults {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Copy to .env and fill in the blanks before `docker compose up -d`.\n")
	for _, n := range names {
		fmt.Fprintf(&b, "%s=%s\n", n, defaults[n])
	}
	return []byte(b.String())
}
